apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: monitoring
  labels:
    app: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx-service
  ports:
    - protocol: TCP
      # name: ngmon
      port: 8082
      targetPort: 9113
