apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mynginx-app
  namespace: monitoring
  labels:
    tier: app-tier
spec:
  selector:
    matchLabels:
      app: nginx-service
  endpoints:
  - port: web
