apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-sm
  namespace: monitoring 
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: prometheus-server
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
