apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoex
  labels:
    tier: app-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app-tier
  template:
    metadata:
      name: my-pod
      labels:
        tier: app-tier
    spec:
      containers:
        - name: mongoex
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: database_url
