apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  # type: NodePort
  selector:
    tier: app-tier
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
