apiVersion: v1
kind: Service
metadata:
  name: mongoex-service
  labels:
    app: mongoex-service
spec:
  # type: NodePort
  selector:
    tier: app-tier
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
