apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-pod
    image: redis
    volumeMounts:
    - name: my-secret-volume
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: my-secret-volume
    secret:
      secretName: my-secret-config
      optional: true
